/*
 * Whisper API Platform
 * Whisper provides comprehensive intelligence and monitoring capabilities for domains, IPs, and web infrastructure. Access powerful APIs for WHOIS data, DNS analysis, screenshot capture, network intelligence, and more - all through a unified, authenticated interface.  **Key Features:** • Domain intelligence and subdomain discovery • IP geolocation and network analysis • Real-time and historical WHOIS data • Automated website screenshot capture • Network relationship mapping • BGP routing and security intelligence • Infrastructure monitoring and health checks  **Authentication:** All endpoints require Bearer token authentication. Contact support for API access.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@whisper.security
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.noctisfrontgraph.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.noctisfrontgraph.sdk.model.DomainerSimilarityType;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Results and status information for an asynchronous domain search request (similarity or free-text)
 */
@JsonPropertyOrder({
  DomainerAsyncResultDTO.JSON_PROPERTY_REQUEST_ID,
  DomainerAsyncResultDTO.JSON_PROPERTY_DOMAIN_NAME,
  DomainerAsyncResultDTO.JSON_PROPERTY_SIMILARITY_TYPE,
  DomainerAsyncResultDTO.JSON_PROPERTY_QUERY_STRING,
  DomainerAsyncResultDTO.JSON_PROPERTY_OPERATOR,
  DomainerAsyncResultDTO.JSON_PROPERTY_LEVEL,
  DomainerAsyncResultDTO.JSON_PROPERTY_LIMIT,
  DomainerAsyncResultDTO.JSON_PROPERTY_CREATED_AT,
  DomainerAsyncResultDTO.JSON_PROPERTY_COMPLETED_AT,
  DomainerAsyncResultDTO.JSON_PROPERTY_STATUS,
  DomainerAsyncResultDTO.JSON_PROPERTY_RESULTS,
  DomainerAsyncResultDTO.JSON_PROPERTY_RESULT_COUNT,
  DomainerAsyncResultDTO.JSON_PROPERTY_PROCESSING_TIME_MS
})
@JsonTypeName("domainer_AsyncResultDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-15T11:53:44.371328345Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class DomainerAsyncResultDTO {
  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  @javax.annotation.Nonnull
  private UUID requestId;

  public static final String JSON_PROPERTY_DOMAIN_NAME = "domainName";
  @javax.annotation.Nullable
  private String domainName;

  public static final String JSON_PROPERTY_SIMILARITY_TYPE = "similarityType";
  @javax.annotation.Nullable
  private DomainerSimilarityType similarityType;

  public static final String JSON_PROPERTY_QUERY_STRING = "queryString";
  @javax.annotation.Nullable
  private JsonNullable<String> queryString = JsonNullable.<String>undefined();

  /**
   * Default operator used between query terms (only for SEARCH requests)
   */
  public enum OperatorEnum {
    AND(String.valueOf("AND")),
    
    OR(String.valueOf("OR"));

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  @javax.annotation.Nullable
  private JsonNullable<OperatorEnum> operator = JsonNullable.<OperatorEnum>undefined();

  /**
   * Absolute domain level filter applied (only for SEARCH requests)
   */
  public enum LevelEnum {
    ALL(String.valueOf("ALL")),
    
    IMMEDIATE(String.valueOf("IMMEDIATE")),
    
    MAX_DEPTH(String.valueOf("MAX_DEPTH"));

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LevelEnum fromValue(String value) {
      for (LevelEnum b : LevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_LEVEL = "level";
  @javax.annotation.Nullable
  private JsonNullable<LevelEnum> level = JsonNullable.<LevelEnum>undefined();

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nonnull
  private Integer limit;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_COMPLETED_AT = "completedAt";
  @javax.annotation.Nullable
  private JsonNullable<OffsetDateTime> completedAt = JsonNullable.<OffsetDateTime>undefined();

  /**
   * Request status
   */
  public enum StatusEnum {
    PROCESSING(String.valueOf("PROCESSING")),
    
    COMPLETED(String.valueOf("COMPLETED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_RESULTS = "results";
  @javax.annotation.Nullable
  private JsonNullable<List<String>> results = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_RESULT_COUNT = "resultCount";
  @javax.annotation.Nullable
  private Integer resultCount;

  public static final String JSON_PROPERTY_PROCESSING_TIME_MS = "processingTimeMs";
  @javax.annotation.Nullable
  private Long processingTimeMs;

  public DomainerAsyncResultDTO() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public DomainerAsyncResultDTO(
    @JsonProperty(JSON_PROPERTY_REQUEST_ID) UUID requestId, 
    @JsonProperty(JSON_PROPERTY_DOMAIN_NAME) String domainName, 
    @JsonProperty(JSON_PROPERTY_QUERY_STRING) String queryString, 
    @JsonProperty(JSON_PROPERTY_OPERATOR) OperatorEnum operator, 
    @JsonProperty(JSON_PROPERTY_LEVEL) LevelEnum level, 
    @JsonProperty(JSON_PROPERTY_LIMIT) Integer limit, 
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_COMPLETED_AT) OffsetDateTime completedAt, 
    @JsonProperty(JSON_PROPERTY_STATUS) StatusEnum status, 
    @JsonProperty(JSON_PROPERTY_RESULTS) List<String> results, 
    @JsonProperty(JSON_PROPERTY_RESULT_COUNT) Integer resultCount, 
    @JsonProperty(JSON_PROPERTY_PROCESSING_TIME_MS) Long processingTimeMs
  ) {
    this();
    this.requestId = requestId;
    this.domainName = domainName;
    this.queryString = queryString == null ? JsonNullable.<String>undefined() : JsonNullable.of(queryString);
    this.operator = operator == null ? JsonNullable.<OperatorEnum>undefined() : JsonNullable.of(operator);
    this.level = level == null ? JsonNullable.<LevelEnum>undefined() : JsonNullable.of(level);
    this.limit = limit;
    this.createdAt = createdAt;
    this.completedAt = completedAt == null ? JsonNullable.<OffsetDateTime>undefined() : JsonNullable.of(completedAt);
    this.status = status;
    this.results = results == null ? JsonNullable.<List<String>>undefined() : JsonNullable.of(results);
    this.resultCount = resultCount;
    this.processingTimeMs = processingTimeMs;
  }

  /**
   * Unique identifier for the request
   * @return requestId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRequestId() {
    return requestId;
  }



  /**
   * Domain name that was searched
   * @return domainName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOMAIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDomainName() {
    return domainName;
  }



  public DomainerAsyncResultDTO similarityType(@javax.annotation.Nullable DomainerSimilarityType similarityType) {
    
    this.similarityType = similarityType;
    return this;
  }

  /**
   * Get similarityType
   * @return similarityType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIMILARITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DomainerSimilarityType getSimilarityType() {
    return similarityType;
  }


  @JsonProperty(JSON_PROPERTY_SIMILARITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSimilarityType(@javax.annotation.Nullable DomainerSimilarityType similarityType) {
    this.similarityType = similarityType;
  }

  /**
   * Query string used for the search (only for SEARCH requests)
   * @return queryString
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getQueryString() {
    
    if (queryString == null) {
      queryString = JsonNullable.<String>undefined();
    }
    return queryString.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_QUERY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getQueryString_JsonNullable() {
    return queryString;
  }
  
  @JsonProperty(JSON_PROPERTY_QUERY_STRING)
  private void setQueryString_JsonNullable(JsonNullable<String> queryString) {
    this.queryString = queryString;
  }


  /**
   * Default operator used between query terms (only for SEARCH requests)
   * @return operator
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public OperatorEnum getOperator() {
    
    if (operator == null) {
      operator = JsonNullable.<OperatorEnum>undefined();
    }
    return operator.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OperatorEnum> getOperator_JsonNullable() {
    return operator;
  }
  
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  private void setOperator_JsonNullable(JsonNullable<OperatorEnum> operator) {
    this.operator = operator;
  }


  /**
   * Absolute domain level filter applied (only for SEARCH requests)
   * @return level
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public LevelEnum getLevel() {
    
    if (level == null) {
      level = JsonNullable.<LevelEnum>undefined();
    }
    return level.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LevelEnum> getLevel_JsonNullable() {
    return level;
  }
  
  @JsonProperty(JSON_PROPERTY_LEVEL)
  private void setLevel_JsonNullable(JsonNullable<LevelEnum> level) {
    this.level = level;
  }


  /**
   * Maximum number of results requested
   * minimum: 1
   * @return limit
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLimit() {
    return limit;
  }



  /**
   * Time when the request was created
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  /**
   * Time when the request was completed (null if still processing)
   * @return completedAt
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCompletedAt() {
    
    if (completedAt == null) {
      completedAt = JsonNullable.<OffsetDateTime>undefined();
    }
    return completedAt.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCompletedAt_JsonNullable() {
    return completedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPLETED_AT)
  private void setCompletedAt_JsonNullable(JsonNullable<OffsetDateTime> completedAt) {
    this.completedAt = completedAt;
  }


  /**
   * Request status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }



  /**
   * List of similar domains found (null if still processing)
   * @return results
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getResults() {
    
    if (results == null) {
      results = JsonNullable.<List<String>>undefined();
    }
    return results.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getResults_JsonNullable() {
    return results;
  }
  
  @JsonProperty(JSON_PROPERTY_RESULTS)
  private void setResults_JsonNullable(JsonNullable<List<String>> results) {
    this.results = results;
  }


  /**
   * Total number of results found
   * minimum: 0
   * @return resultCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResultCount() {
    return resultCount;
  }



  /**
   * Time taken to process the request in milliseconds (-1 if still processing)
   * minimum: -1
   * @return processingTimeMs
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSING_TIME_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProcessingTimeMs() {
    return processingTimeMs;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainerAsyncResultDTO domainerAsyncResultDTO = (DomainerAsyncResultDTO) o;
    return Objects.equals(this.requestId, domainerAsyncResultDTO.requestId) &&
        Objects.equals(this.domainName, domainerAsyncResultDTO.domainName) &&
        Objects.equals(this.similarityType, domainerAsyncResultDTO.similarityType) &&
        equalsNullable(this.queryString, domainerAsyncResultDTO.queryString) &&
        equalsNullable(this.operator, domainerAsyncResultDTO.operator) &&
        equalsNullable(this.level, domainerAsyncResultDTO.level) &&
        Objects.equals(this.limit, domainerAsyncResultDTO.limit) &&
        Objects.equals(this.createdAt, domainerAsyncResultDTO.createdAt) &&
        equalsNullable(this.completedAt, domainerAsyncResultDTO.completedAt) &&
        Objects.equals(this.status, domainerAsyncResultDTO.status) &&
        equalsNullable(this.results, domainerAsyncResultDTO.results) &&
        Objects.equals(this.resultCount, domainerAsyncResultDTO.resultCount) &&
        Objects.equals(this.processingTimeMs, domainerAsyncResultDTO.processingTimeMs);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, domainName, similarityType, hashCodeNullable(queryString), hashCodeNullable(operator), hashCodeNullable(level), limit, createdAt, hashCodeNullable(completedAt), status, hashCodeNullable(results), resultCount, processingTimeMs);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainerAsyncResultDTO {\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    similarityType: ").append(toIndentedString(similarityType)).append("\n");
    sb.append("    queryString: ").append(toIndentedString(queryString)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
    sb.append("    processingTimeMs: ").append(toIndentedString(processingTimeMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

