/*
 * Whisper API Platform
 * Whisper provides comprehensive intelligence and monitoring capabilities for domains, IPs, and web infrastructure. Access powerful APIs for WHOIS data, DNS analysis, screenshot capture, network intelligence, and more - all through a unified, authenticated interface.  **Key Features:** • Domain intelligence and subdomain discovery • IP geolocation and network analysis • Real-time and historical WHOIS data • Automated website screenshot capture • Network relationship mapping • BGP routing and security intelligence • Infrastructure monitoring and health checks  **Authentication:** All endpoints require Bearer token authentication. Contact support for API access.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@whisper.security
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.noctisfrontgraph.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of similarity that was used for the search
 */
public enum DomainerSimilarityType {
  
  CONTAINS("CONTAINS"),
  
  PREFIX("PREFIX"),
  
  SUFFIX("SUFFIX"),
  
  TYPO("TYPO"),
  
  SOUNDING("SOUNDING"),
  
  UTFVARS("UTFVARS"),
  
  TLD_VARIANTS("TLD_VARIANTS"),
  
  TYPO_OR_SOUNDING("TYPO_OR_SOUNDING"),
  
  LEVENSHTEIN("LEVENSHTEIN");

  private String value;

  DomainerSimilarityType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DomainerSimilarityType fromValue(String value) {
    for (DomainerSimilarityType b : DomainerSimilarityType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

