/*
 * Whisper API Platform
 * Whisper provides comprehensive intelligence and monitoring capabilities for domains, IPs, and web infrastructure. Access powerful APIs for WHOIS data, DNS analysis, screenshot capture, network intelligence, and more - all through a unified, authenticated interface.  **Key Features:** • Domain intelligence and subdomain discovery • IP geolocation and network analysis • Real-time and historical WHOIS data • Automated website screenshot capture • Network relationship mapping • BGP routing and security intelligence • Infrastructure monitoring and health checks  **Authentication:** All endpoints require Bearer token authentication. Contact support for API access.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@whisper.security
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.noctisfrontgraph.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * IpIntelligenceResponseGeolocationCountry
 */
@JsonPropertyOrder({
  IpIntelligenceResponseGeolocationCountry.JSON_PROPERTY_ISO_CODE,
  IpIntelligenceResponseGeolocationCountry.JSON_PROPERTY_NAME,
  IpIntelligenceResponseGeolocationCountry.JSON_PROPERTY_CONFIDENCE
})
@JsonTypeName("IpIntelligenceResponse_geolocation_country")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-15T11:53:44.371328345Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class IpIntelligenceResponseGeolocationCountry {
  public static final String JSON_PROPERTY_ISO_CODE = "iso_code";
  @javax.annotation.Nullable
  private String isoCode;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @javax.annotation.Nullable
  private Integer confidence;

  public IpIntelligenceResponseGeolocationCountry() {
  }

  public IpIntelligenceResponseGeolocationCountry isoCode(@javax.annotation.Nullable String isoCode) {
    
    this.isoCode = isoCode;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 code
   * @return isoCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIsoCode() {
    return isoCode;
  }


  @JsonProperty(JSON_PROPERTY_ISO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsoCode(@javax.annotation.Nullable String isoCode) {
    this.isoCode = isoCode;
  }

  public IpIntelligenceResponseGeolocationCountry name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Country name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public IpIntelligenceResponseGeolocationCountry confidence(@javax.annotation.Nullable Integer confidence) {
    
    this.confidence = confidence;
    return this;
  }

  /**
   * Confidence score (0-100)
   * @return confidence
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getConfidence() {
    return confidence;
  }


  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfidence(@javax.annotation.Nullable Integer confidence) {
    this.confidence = confidence;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpIntelligenceResponseGeolocationCountry ipIntelligenceResponseGeolocationCountry = (IpIntelligenceResponseGeolocationCountry) o;
    return Objects.equals(this.isoCode, ipIntelligenceResponseGeolocationCountry.isoCode) &&
        Objects.equals(this.name, ipIntelligenceResponseGeolocationCountry.name) &&
        Objects.equals(this.confidence, ipIntelligenceResponseGeolocationCountry.confidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isoCode, name, confidence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpIntelligenceResponseGeolocationCountry {\n");
    sb.append("    isoCode: ").append(toIndentedString(isoCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

