/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BlacklistScores
 */
class BlacklistScoresTest {
    private final BlacklistScores model = new BlacklistScores();

    /**
     * Model tests for BlacklistScores
     */
    @Test
    void testBlacklistScores() {
        // TODO: test BlacklistScores
    }

    /**
     * Test the property 'ipScore'
     */
    @Test
    void ipScoreTest() {
        // TODO: test ipScore
    }

    /**
     * Test the property 'prefixScore'
     */
    @Test
    void prefixScoreTest() {
        // TODO: test prefixScore
    }

    /**
     * Test the property 'asnScore'
     */
    @Test
    void asnScoreTest() {
        // TODO: test asnScore
    }

}
