/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BulkOptions
 */
class BulkOptionsTest {
    private final BulkOptions model = new BulkOptions();

    /**
     * Model tests for BulkOptions
     */
    @Test
    void testBulkOptions() {
        // TODO: test BulkOptions
    }

    /**
     * Test the property 'parallelProcessing'
     */
    @Test
    void parallelProcessingTest() {
        // TODO: test parallelProcessing
    }

    /**
     * Test the property 'batchSize'
     */
    @Test
    void batchSizeTest() {
        // TODO: test batchSize
    }

    /**
     * Test the property 'timeoutPerIndicator'
     */
    @Test
    void timeoutPerIndicatorTest() {
        // TODO: test timeoutPerIndicator
    }

    /**
     * Test the property 'continueOnError'
     */
    @Test
    void continueOnErrorTest() {
        // TODO: test continueOnError
    }

    /**
     * Test the property 'includeFailed'
     */
    @Test
    void includeFailedTest() {
        // TODO: test includeFailed
    }

}
