/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CurrentAssessment
 */
class CurrentAssessmentTest {
    private final CurrentAssessment model = new CurrentAssessment();

    /**
     * Model tests for CurrentAssessment
     */
    @Test
    void testCurrentAssessment() {
        // TODO: test CurrentAssessment
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'riskScore'
     */
    @Test
    void riskScoreTest() {
        // TODO: test riskScore
    }

    /**
     * Test the property 'riskLevel'
     */
    @Test
    void riskLevelTest() {
        // TODO: test riskLevel
    }

    /**
     * Test the property 'assessedAt'
     */
    @Test
    void assessedAtTest() {
        // TODO: test assessedAt
    }

}
