/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.whispersec.model.DomainReputationDetails;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DomainReputationScores
 */
class DomainReputationScoresTest {
    private final DomainReputationScores model = new DomainReputationScores();

    /**
     * Model tests for DomainReputationScores
     */
    @Test
    void testDomainReputationScores() {
        // TODO: test DomainReputationScores
    }

    /**
     * Test the property 'overallScore'
     */
    @Test
    void overallScoreTest() {
        // TODO: test overallScore
    }

    /**
     * Test the property 'riskLevel'
     */
    @Test
    void riskLevelTest() {
        // TODO: test riskLevel
    }

    /**
     * Test the property 'domainIpScore'
     */
    @Test
    void domainIpScoreTest() {
        // TODO: test domainIpScore
    }

    /**
     * Test the property 'nameserverIpScore'
     */
    @Test
    void nameserverIpScoreTest() {
        // TODO: test nameserverIpScore
    }

    /**
     * Test the property 'mailserverIpScore'
     */
    @Test
    void mailserverIpScoreTest() {
        // TODO: test mailserverIpScore
    }

    /**
     * Test the property 'details'
     */
    @Test
    void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'scoringMethod'
     */
    @Test
    void scoringMethodTest() {
        // TODO: test scoringMethod
    }

    /**
     * Test the property 'weights'
     */
    @Test
    void weightsTest() {
        // TODO: test weights
    }

}
