/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HomoglyphConfig
 */
class HomoglyphConfigTest {
    private final HomoglyphConfig model = new HomoglyphConfig();

    /**
     * Model tests for HomoglyphConfig
     */
    @Test
    void testHomoglyphConfig() {
        // TODO: test HomoglyphConfig
    }

    /**
     * Test the property 'cyrillic'
     */
    @Test
    void cyrillicTest() {
        // TODO: test cyrillic
    }

    /**
     * Test the property 'greek'
     */
    @Test
    void greekTest() {
        // TODO: test greek
    }

    /**
     * Test the property 'latin'
     */
    @Test
    void latinTest() {
        // TODO: test latin
    }

    /**
     * Test the property 'maxSubstitutions'
     */
    @Test
    void maxSubstitutionsTest() {
        // TODO: test maxSubstitutions
    }

}
