/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.whispersec.model.DnsInfo;
import io.github.whispersec.model.MetadataInfo;
import io.github.whispersec.model.QueryInfo;
import io.github.whispersec.model.RelationshipInfo;
import io.github.whispersec.model.ReputationInfo;
import io.github.whispersec.model.SummaryInfo;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IndicatorResponse
 */
class IndicatorResponseTest {
    private final IndicatorResponse model = new IndicatorResponse();

    /**
     * Model tests for IndicatorResponse
     */
    @Test
    void testIndicatorResponse() {
        // TODO: test IndicatorResponse
    }

    /**
     * Test the property 'query'
     */
    @Test
    void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'summary'
     */
    @Test
    void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'geolocation'
     */
    @Test
    void geolocationTest() {
        // TODO: test geolocation
    }

    /**
     * Test the property 'network'
     */
    @Test
    void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'routing'
     */
    @Test
    void routingTest() {
        // TODO: test routing
    }

    /**
     * Test the property 'isp'
     */
    @Test
    void ispTest() {
        // TODO: test isp
    }

    /**
     * Test the property 'registration'
     */
    @Test
    void registrationTest() {
        // TODO: test registration
    }

    /**
     * Test the property 'dns'
     */
    @Test
    void dnsTest() {
        // TODO: test dns
    }

    /**
     * Test the property 'relationships'
     */
    @Test
    void relationshipsTest() {
        // TODO: test relationships
    }

    /**
     * Test the property 'reputation'
     */
    @Test
    void reputationTest() {
        // TODO: test reputation
    }

    /**
     * Test the property 'security'
     */
    @Test
    void securityTest() {
        // TODO: test security
    }

    /**
     * Test the property 'rpki'
     */
    @Test
    void rpkiTest() {
        // TODO: test rpki
    }

    /**
     * Test the property 'ipIntelligence'
     */
    @Test
    void ipIntelligenceTest() {
        // TODO: test ipIntelligence
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
