/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.whispersec.model.InvestigateContext;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvestigateRequest
 */
class InvestigateRequestTest {
    private final InvestigateRequest model = new InvestigateRequest();

    /**
     * Model tests for InvestigateRequest
     */
    @Test
    void testInvestigateRequest() {
        // TODO: test InvestigateRequest
    }

    /**
     * Test the property 'indicator'
     */
    @Test
    void indicatorTest() {
        // TODO: test indicator
    }

    /**
     * Test the property 'indicatorType'
     */
    @Test
    void indicatorTypeTest() {
        // TODO: test indicatorType
    }

    /**
     * Test the property 'depth'
     */
    @Test
    void depthTest() {
        // TODO: test depth
    }

    /**
     * Test the property 'context'
     */
    @Test
    void contextTest() {
        // TODO: test context
    }

}
