/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobResponse
 */
class JobResponseTest {
    private final JobResponse model = new JobResponse();

    /**
     * Model tests for JobResponse
     */
    @Test
    void testJobResponse() {
        // TODO: test JobResponse
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusUrl'
     */
    @Test
    void statusUrlTest() {
        // TODO: test statusUrl
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

}
