/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MonitorAssertions
 */
class MonitorAssertionsTest {
    private final MonitorAssertions model = new MonitorAssertions();

    /**
     * Model tests for MonitorAssertions
     */
    @Test
    void testMonitorAssertions() {
        // TODO: test MonitorAssertions
    }

    /**
     * Test the property 'headers'
     */
    @Test
    void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'maxResponseTime'
     */
    @Test
    void maxResponseTimeTest() {
        // TODO: test maxResponseTime
    }

    /**
     * Test the property 'containsText'
     */
    @Test
    void containsTextTest() {
        // TODO: test containsText
    }

    /**
     * Test the property 'notContainsText'
     */
    @Test
    void notContainsTextTest() {
        // TODO: test notContainsText
    }

    /**
     * Test the property 'sslDaysUntilExpiry'
     */
    @Test
    void sslDaysUntilExpiryTest() {
        // TODO: test sslDaysUntilExpiry
    }

    /**
     * Test the property 'dnsRecordValue'
     */
    @Test
    void dnsRecordValueTest() {
        // TODO: test dnsRecordValue
    }

    /**
     * Test the property 'dnsRecordType'
     */
    @Test
    void dnsRecordTypeTest() {
        // TODO: test dnsRecordType
    }

}
