/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PatternMatching
 */
class PatternMatchingTest {
    private final PatternMatching model = new PatternMatching();

    /**
     * Model tests for PatternMatching
     */
    @Test
    void testPatternMatching() {
        // TODO: test PatternMatching
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'matchedPatterns'
     */
    @Test
    void matchedPatternsTest() {
        // TODO: test matchedPatterns
    }

}
