/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.whispersec.model.BitsquattingConfig;
import io.github.whispersec.model.HomoglyphConfig;
import io.github.whispersec.model.TldVariationConfig;
import io.github.whispersec.model.TyposquattingConfig;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TechniqueConfig
 */
class TechniqueConfigTest {
    private final TechniqueConfig model = new TechniqueConfig();

    /**
     * Model tests for TechniqueConfig
     */
    @Test
    void testTechniqueConfig() {
        // TODO: test TechniqueConfig
    }

    /**
     * Test the property 'typosquatting'
     */
    @Test
    void typosquattingTest() {
        // TODO: test typosquatting
    }

    /**
     * Test the property 'homoglyph'
     */
    @Test
    void homoglyphTest() {
        // TODO: test homoglyph
    }

    /**
     * Test the property 'bitsquatting'
     */
    @Test
    void bitsquattingTest() {
        // TODO: test bitsquatting
    }

    /**
     * Test the property 'tldVariation'
     */
    @Test
    void tldVariationTest() {
        // TODO: test tldVariation
    }

}
