/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Attribution context information
 */
@JsonPropertyOrder({
  AttributionContext.JSON_PROPERTY_OBSERVED_T_T_PS,
  AttributionContext.JSON_PROPERTY_TARGETED_SECTOR,
  AttributionContext.JSON_PROPERTY_TARGET_REGION,
  AttributionContext.JSON_PROPERTY_TIMEFRAME,
  AttributionContext.JSON_PROPERTY_MALWARE_FAMILIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T18:46:57.209997094Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class AttributionContext {
  public static final String JSON_PROPERTY_OBSERVED_T_T_PS = "observedTTPs";
  @jakarta.annotation.Nullable
  private List<String> observedTTPs = new ArrayList<>();

  public static final String JSON_PROPERTY_TARGETED_SECTOR = "targetedSector";
  @jakarta.annotation.Nullable
  private String targetedSector;

  public static final String JSON_PROPERTY_TARGET_REGION = "targetRegion";
  @jakarta.annotation.Nullable
  private String targetRegion;

  public static final String JSON_PROPERTY_TIMEFRAME = "timeframe";
  @jakarta.annotation.Nullable
  private String timeframe;

  public static final String JSON_PROPERTY_MALWARE_FAMILIES = "malwareFamilies";
  @jakarta.annotation.Nullable
  private List<String> malwareFamilies = new ArrayList<>();

  public AttributionContext() {
  }

  public AttributionContext observedTTPs(@jakarta.annotation.Nullable List<String> observedTTPs) {
    
    this.observedTTPs = observedTTPs;
    return this;
  }

  public AttributionContext addObservedTTPsItem(String observedTTPsItem) {
    if (this.observedTTPs == null) {
      this.observedTTPs = new ArrayList<>();
    }
    this.observedTTPs.add(observedTTPsItem);
    return this;
  }

  /**
   * Observed MITRE ATT&amp;CK TTPs
   * @return observedTTPs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBSERVED_T_T_PS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getObservedTTPs() {
    return observedTTPs;
  }


  @JsonProperty(value = JSON_PROPERTY_OBSERVED_T_T_PS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObservedTTPs(@jakarta.annotation.Nullable List<String> observedTTPs) {
    this.observedTTPs = observedTTPs;
  }

  public AttributionContext targetedSector(@jakarta.annotation.Nullable String targetedSector) {
    
    this.targetedSector = targetedSector;
    return this;
  }

  /**
   * Targeted sector/industry
   * @return targetedSector
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGETED_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetedSector() {
    return targetedSector;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGETED_SECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetedSector(@jakarta.annotation.Nullable String targetedSector) {
    this.targetedSector = targetedSector;
  }

  public AttributionContext targetRegion(@jakarta.annotation.Nullable String targetRegion) {
    
    this.targetRegion = targetRegion;
    return this;
  }

  /**
   * Geographic region of targets
   * @return targetRegion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET_REGION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetRegion() {
    return targetRegion;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_REGION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetRegion(@jakarta.annotation.Nullable String targetRegion) {
    this.targetRegion = targetRegion;
  }

  public AttributionContext timeframe(@jakarta.annotation.Nullable String timeframe) {
    
    this.timeframe = timeframe;
    return this;
  }

  /**
   * Campaign timeframe
   * @return timeframe
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEFRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeframe() {
    return timeframe;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEFRAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeframe(@jakarta.annotation.Nullable String timeframe) {
    this.timeframe = timeframe;
  }

  public AttributionContext malwareFamilies(@jakarta.annotation.Nullable List<String> malwareFamilies) {
    
    this.malwareFamilies = malwareFamilies;
    return this;
  }

  public AttributionContext addMalwareFamiliesItem(String malwareFamiliesItem) {
    if (this.malwareFamilies == null) {
      this.malwareFamilies = new ArrayList<>();
    }
    this.malwareFamilies.add(malwareFamiliesItem);
    return this;
  }

  /**
   * Known malware families observed
   * @return malwareFamilies
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MALWARE_FAMILIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getMalwareFamilies() {
    return malwareFamilies;
  }


  @JsonProperty(value = JSON_PROPERTY_MALWARE_FAMILIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMalwareFamilies(@jakarta.annotation.Nullable List<String> malwareFamilies) {
    this.malwareFamilies = malwareFamilies;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributionContext attributionContext = (AttributionContext) o;
    return Objects.equals(this.observedTTPs, attributionContext.observedTTPs) &&
        Objects.equals(this.targetedSector, attributionContext.targetedSector) &&
        Objects.equals(this.targetRegion, attributionContext.targetRegion) &&
        Objects.equals(this.timeframe, attributionContext.timeframe) &&
        Objects.equals(this.malwareFamilies, attributionContext.malwareFamilies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(observedTTPs, targetedSector, targetRegion, timeframe, malwareFamilies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributionContext {\n");
    sb.append("    observedTTPs: ").append(toIndentedString(observedTTPs)).append("\n");
    sb.append("    targetedSector: ").append(toIndentedString(targetedSector)).append("\n");
    sb.append("    targetRegion: ").append(toIndentedString(targetRegion)).append("\n");
    sb.append("    timeframe: ").append(toIndentedString(timeframe)).append("\n");
    sb.append("    malwareFamilies: ").append(toIndentedString(malwareFamilies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

