/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * HistoryData
 */
@JsonPropertyOrder({
  HistoryData.JSON_PROPERTY_RECORDS,
  HistoryData.JSON_PROPERTY_TOTAL_RECORDS,
  HistoryData.JSON_PROPERTY_OLDEST_DATE,
  HistoryData.JSON_PROPERTY_NEWEST_DATE,
  HistoryData.JSON_PROPERTY_MESSAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-01T14:38:21.899985563Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class HistoryData {
  public static final String JSON_PROPERTY_RECORDS = "records";
  @jakarta.annotation.Nullable
  private List<Object> records = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_RECORDS = "total_records";
  @jakarta.annotation.Nullable
  private Integer totalRecords;

  public static final String JSON_PROPERTY_OLDEST_DATE = "oldest_date";
  @jakarta.annotation.Nullable
  private String oldestDate;

  public static final String JSON_PROPERTY_NEWEST_DATE = "newest_date";
  @jakarta.annotation.Nullable
  private String newestDate;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public HistoryData() {
  }

  public HistoryData records(@jakarta.annotation.Nullable List<Object> records) {
    
    this.records = records;
    return this;
  }

  public HistoryData addRecordsItem(Object recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Get records
   * @return records
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECORDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getRecords() {
    return records;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecords(@jakarta.annotation.Nullable List<Object> records) {
    this.records = records;
  }

  public HistoryData totalRecords(@jakarta.annotation.Nullable Integer totalRecords) {
    
    this.totalRecords = totalRecords;
    return this;
  }

  /**
   * Get totalRecords
   * @return totalRecords
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_RECORDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalRecords() {
    return totalRecords;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_RECORDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRecords(@jakarta.annotation.Nullable Integer totalRecords) {
    this.totalRecords = totalRecords;
  }

  public HistoryData oldestDate(@jakarta.annotation.Nullable String oldestDate) {
    
    this.oldestDate = oldestDate;
    return this;
  }

  /**
   * Get oldestDate
   * @return oldestDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OLDEST_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOldestDate() {
    return oldestDate;
  }


  @JsonProperty(value = JSON_PROPERTY_OLDEST_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOldestDate(@jakarta.annotation.Nullable String oldestDate) {
    this.oldestDate = oldestDate;
  }

  public HistoryData newestDate(@jakarta.annotation.Nullable String newestDate) {
    
    this.newestDate = newestDate;
    return this;
  }

  /**
   * Get newestDate
   * @return newestDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEWEST_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNewestDate() {
    return newestDate;
  }


  @JsonProperty(value = JSON_PROPERTY_NEWEST_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewestDate(@jakarta.annotation.Nullable String newestDate) {
    this.newestDate = newestDate;
  }

  public HistoryData message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryData historyData = (HistoryData) o;
    return Objects.equals(this.records, historyData.records) &&
        Objects.equals(this.totalRecords, historyData.totalRecords) &&
        Objects.equals(this.oldestDate, historyData.oldestDate) &&
        Objects.equals(this.newestDate, historyData.newestDate) &&
        Objects.equals(this.message, historyData.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, totalRecords, oldestDate, newestDate, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryData {\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    oldestDate: ").append(toIndentedString(oldestDate)).append("\n");
    sb.append("    newestDate: ").append(toIndentedString(newestDate)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

