/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ML model information
 */
@JsonPropertyOrder({
  ModelInfo.JSON_PROPERTY_VERSION,
  ModelInfo.JSON_PROPERTY_LAST_UPDATED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T18:46:57.209997094Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class ModelInfo {
  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private String version;

  public static final String JSON_PROPERTY_LAST_UPDATED = "lastUpdated";
  @jakarta.annotation.Nullable
  private String lastUpdated;

  public ModelInfo() {
  }

  public ModelInfo version(@jakarta.annotation.Nullable String version) {
    
    this.version = version;
    return this;
  }

  /**
   * Model version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable String version) {
    this.version = version;
  }

  public ModelInfo lastUpdated(@jakarta.annotation.Nullable String lastUpdated) {
    
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * Last updated timestamp
   * @return lastUpdated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastUpdated() {
    return lastUpdated;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdated(@jakarta.annotation.Nullable String lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelInfo modelInfo = (ModelInfo) o;
    return Objects.equals(this.version, modelInfo.version) &&
        Objects.equals(this.lastUpdated, modelInfo.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelInfo {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

