/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Configuration for creating monitoring alert rules with notification channels
 */
@JsonPropertyOrder({
  MonitoringAlertRequest.JSON_PROPERTY_TYPE,
  MonitoringAlertRequest.JSON_PROPERTY_THRESHOLD_DAYS,
  MonitoringAlertRequest.JSON_PROPERTY_CHANNELS,
  MonitoringAlertRequest.JSON_PROPERTY_EMAIL,
  MonitoringAlertRequest.JSON_PROPERTY_SLACK_WEBHOOK,
  MonitoringAlertRequest.JSON_PROPERTY_WEBHOOK_URL,
  MonitoringAlertRequest.JSON_PROPERTY_PAGERDUTY_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-01T14:38:21.899985563Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class MonitoringAlertRequest {
  /**
   * Type of alert condition to monitor
   */
  public enum TypeEnum {
    DOWNTIME(String.valueOf("downtime")),
    
    DNS_CHANGE(String.valueOf("dns_change")),
    
    WHOIS_CHANGE(String.valueOf("whois_change")),
    
    SSL_EXPIRING(String.valueOf("ssl_expiring")),
    
    CONTENT_CHANGE(String.valueOf("content_change")),
    
    TECHNOLOGY_CHANGE(String.valueOf("technology_change"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_THRESHOLD_DAYS = "threshold_days";
  @jakarta.annotation.Nullable
  private Integer thresholdDays;

  public static final String JSON_PROPERTY_CHANNELS = "channels";
  @jakarta.annotation.Nullable
  private Set<String> channels = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_SLACK_WEBHOOK = "slack_webhook";
  @jakarta.annotation.Nullable
  private String slackWebhook;

  public static final String JSON_PROPERTY_WEBHOOK_URL = "webhook_url";
  @jakarta.annotation.Nullable
  private String webhookUrl;

  public static final String JSON_PROPERTY_PAGERDUTY_KEY = "pagerduty_key";
  @jakarta.annotation.Nullable
  private String pagerdutyKey;

  public MonitoringAlertRequest() {
  }

  public MonitoringAlertRequest type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Type of alert condition to monitor
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public MonitoringAlertRequest thresholdDays(@jakarta.annotation.Nullable Integer thresholdDays) {
    
    this.thresholdDays = thresholdDays;
    return this;
  }

  /**
   * Threshold in days (for ssl_expiring alerts). Alert triggers when SSL cert expires within this many days.
   * minimum: 1
   * @return thresholdDays
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THRESHOLD_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getThresholdDays() {
    return thresholdDays;
  }


  @JsonProperty(value = JSON_PROPERTY_THRESHOLD_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThresholdDays(@jakarta.annotation.Nullable Integer thresholdDays) {
    this.thresholdDays = thresholdDays;
  }

  public MonitoringAlertRequest channels(@jakarta.annotation.Nullable Set<String> channels) {
    
    this.channels = channels;
    return this;
  }

  public MonitoringAlertRequest addChannelsItem(String channelsItem) {
    if (this.channels == null) {
      this.channels = new LinkedHashSet<>();
    }
    this.channels.add(channelsItem);
    return this;
  }

  /**
   * Notification channels to use for alerts
   * @return channels
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANNELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getChannels() {
    return channels;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_CHANNELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannels(@jakarta.annotation.Nullable Set<String> channels) {
    this.channels = channels;
  }

  public MonitoringAlertRequest email(@jakarta.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Email address for alert notifications
   * @return email
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@jakarta.annotation.Nullable String email) {
    this.email = email;
  }

  public MonitoringAlertRequest slackWebhook(@jakarta.annotation.Nullable String slackWebhook) {
    
    this.slackWebhook = slackWebhook;
    return this;
  }

  /**
   * Slack webhook URL for notifications
   * @return slackWebhook
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SLACK_WEBHOOK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSlackWebhook() {
    return slackWebhook;
  }


  @JsonProperty(value = JSON_PROPERTY_SLACK_WEBHOOK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSlackWebhook(@jakarta.annotation.Nullable String slackWebhook) {
    this.slackWebhook = slackWebhook;
  }

  public MonitoringAlertRequest webhookUrl(@jakarta.annotation.Nullable String webhookUrl) {
    
    this.webhookUrl = webhookUrl;
    return this;
  }

  /**
   * Custom webhook URL for notifications (will receive POST with alert data)
   * @return webhookUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebhookUrl() {
    return webhookUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookUrl(@jakarta.annotation.Nullable String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }

  public MonitoringAlertRequest pagerdutyKey(@jakarta.annotation.Nullable String pagerdutyKey) {
    
    this.pagerdutyKey = pagerdutyKey;
    return this;
  }

  /**
   * PagerDuty integration key for incident creation
   * @return pagerdutyKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGERDUTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPagerdutyKey() {
    return pagerdutyKey;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGERDUTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagerdutyKey(@jakarta.annotation.Nullable String pagerdutyKey) {
    this.pagerdutyKey = pagerdutyKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonitoringAlertRequest monitoringAlertRequest = (MonitoringAlertRequest) o;
    return Objects.equals(this.type, monitoringAlertRequest.type) &&
        Objects.equals(this.thresholdDays, monitoringAlertRequest.thresholdDays) &&
        Objects.equals(this.channels, monitoringAlertRequest.channels) &&
        Objects.equals(this.email, monitoringAlertRequest.email) &&
        Objects.equals(this.slackWebhook, monitoringAlertRequest.slackWebhook) &&
        Objects.equals(this.webhookUrl, monitoringAlertRequest.webhookUrl) &&
        Objects.equals(this.pagerdutyKey, monitoringAlertRequest.pagerdutyKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, thresholdDays, channels, email, slackWebhook, webhookUrl, pagerdutyKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonitoringAlertRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    thresholdDays: ").append(toIndentedString(thresholdDays)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    slackWebhook: ").append(toIndentedString(slackWebhook)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    pagerdutyKey: ").append(toIndentedString(pagerdutyKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

