/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Configuration options for screenshot capture
 */
@JsonPropertyOrder({
  ScreenshotOptions.JSON_PROPERTY_WIDTH,
  ScreenshotOptions.JSON_PROPERTY_HEIGHT,
  ScreenshotOptions.JSON_PROPERTY_FULL_PAGE,
  ScreenshotOptions.JSON_PROPERTY_WAIT_TIME,
  ScreenshotOptions.JSON_PROPERTY_FORMAT,
  ScreenshotOptions.JSON_PROPERTY_QUALITY,
  ScreenshotOptions.JSON_PROPERTY_USER_AGENT,
  ScreenshotOptions.JSON_PROPERTY_JAVASCRIPT,
  ScreenshotOptions.JSON_PROPERTY_BLOCK_ADS,
  ScreenshotOptions.JSON_PROPERTY_ACCEPT_COOKIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-01T14:38:21.899985563Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class ScreenshotOptions {
  public static final String JSON_PROPERTY_WIDTH = "width";
  @jakarta.annotation.Nullable
  private Integer width = 1920;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @jakarta.annotation.Nullable
  private Integer height = 1080;

  public static final String JSON_PROPERTY_FULL_PAGE = "full_page";
  @jakarta.annotation.Nullable
  private Boolean fullPage = false;

  public static final String JSON_PROPERTY_WAIT_TIME = "wait_time";
  @jakarta.annotation.Nullable
  private Integer waitTime = 2000;

  /**
   * Image format for the screenshot
   */
  public enum FormatEnum {
    PNG(String.valueOf("png")),
    
    JPEG(String.valueOf("jpeg")),
    
    WEBP(String.valueOf("webp"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private FormatEnum format = FormatEnum.PNG;

  public static final String JSON_PROPERTY_QUALITY = "quality";
  @jakarta.annotation.Nullable
  private Integer quality = 90;

  public static final String JSON_PROPERTY_USER_AGENT = "user_agent";
  @jakarta.annotation.Nullable
  private String userAgent;

  public static final String JSON_PROPERTY_JAVASCRIPT = "javascript";
  @jakarta.annotation.Nullable
  private Boolean javascript = true;

  public static final String JSON_PROPERTY_BLOCK_ADS = "block_ads";
  @jakarta.annotation.Nullable
  private Boolean blockAds = false;

  public static final String JSON_PROPERTY_ACCEPT_COOKIES = "accept_cookies";
  @jakarta.annotation.Nullable
  private Boolean acceptCookies = true;

  public ScreenshotOptions() {
  }

  public ScreenshotOptions width(@jakarta.annotation.Nullable Integer width) {
    
    this.width = width;
    return this;
  }

  /**
   * Viewport width in pixels
   * minimum: 320
   * maximum: 7680
   * @return width
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(@jakarta.annotation.Nullable Integer width) {
    this.width = width;
  }

  public ScreenshotOptions height(@jakarta.annotation.Nullable Integer height) {
    
    this.height = height;
    return this;
  }

  /**
   * Viewport height in pixels
   * minimum: 240
   * maximum: 4320
   * @return height
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(@jakarta.annotation.Nullable Integer height) {
    this.height = height;
  }

  public ScreenshotOptions fullPage(@jakarta.annotation.Nullable Boolean fullPage) {
    
    this.fullPage = fullPage;
    return this;
  }

  /**
   * Capture the full page height (scrolling screenshot)
   * @return fullPage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FULL_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFullPage() {
    return fullPage;
  }


  @JsonProperty(value = JSON_PROPERTY_FULL_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullPage(@jakarta.annotation.Nullable Boolean fullPage) {
    this.fullPage = fullPage;
  }

  public ScreenshotOptions waitTime(@jakarta.annotation.Nullable Integer waitTime) {
    
    this.waitTime = waitTime;
    return this;
  }

  /**
   * Wait time in milliseconds before taking screenshot
   * minimum: 0
   * maximum: 30000
   * @return waitTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WAIT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWaitTime() {
    return waitTime;
  }


  @JsonProperty(value = JSON_PROPERTY_WAIT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWaitTime(@jakarta.annotation.Nullable Integer waitTime) {
    this.waitTime = waitTime;
  }

  public ScreenshotOptions format(@jakarta.annotation.Nullable FormatEnum format) {
    
    this.format = format;
    return this;
  }

  /**
   * Image format for the screenshot
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@jakarta.annotation.Nullable FormatEnum format) {
    this.format = format;
  }

  public ScreenshotOptions quality(@jakarta.annotation.Nullable Integer quality) {
    
    this.quality = quality;
    return this;
  }

  /**
   * Image quality (1-100, only for jpeg/webp)
   * minimum: 1
   * maximum: 100
   * @return quality
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuality() {
    return quality;
  }


  @JsonProperty(value = JSON_PROPERTY_QUALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuality(@jakarta.annotation.Nullable Integer quality) {
    this.quality = quality;
  }

  public ScreenshotOptions userAgent(@jakarta.annotation.Nullable String userAgent) {
    
    this.userAgent = userAgent;
    return this;
  }

  /**
   * User agent string to use for the request
   * @return userAgent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserAgent() {
    return userAgent;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAgent(@jakarta.annotation.Nullable String userAgent) {
    this.userAgent = userAgent;
  }

  public ScreenshotOptions javascript(@jakarta.annotation.Nullable Boolean javascript) {
    
    this.javascript = javascript;
    return this;
  }

  /**
   * Enable JavaScript execution
   * @return javascript
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_JAVASCRIPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getJavascript() {
    return javascript;
  }


  @JsonProperty(value = JSON_PROPERTY_JAVASCRIPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJavascript(@jakarta.annotation.Nullable Boolean javascript) {
    this.javascript = javascript;
  }

  public ScreenshotOptions blockAds(@jakarta.annotation.Nullable Boolean blockAds) {
    
    this.blockAds = blockAds;
    return this;
  }

  /**
   * Block ads and trackers
   * @return blockAds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BLOCK_ADS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBlockAds() {
    return blockAds;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCK_ADS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockAds(@jakarta.annotation.Nullable Boolean blockAds) {
    this.blockAds = blockAds;
  }

  public ScreenshotOptions acceptCookies(@jakarta.annotation.Nullable Boolean acceptCookies) {
    
    this.acceptCookies = acceptCookies;
    return this;
  }

  /**
   * Accept cookies consent if prompted
   * @return acceptCookies
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCEPT_COOKIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAcceptCookies() {
    return acceptCookies;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCEPT_COOKIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptCookies(@jakarta.annotation.Nullable Boolean acceptCookies) {
    this.acceptCookies = acceptCookies;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreenshotOptions screenshotOptions = (ScreenshotOptions) o;
    return Objects.equals(this.width, screenshotOptions.width) &&
        Objects.equals(this.height, screenshotOptions.height) &&
        Objects.equals(this.fullPage, screenshotOptions.fullPage) &&
        Objects.equals(this.waitTime, screenshotOptions.waitTime) &&
        Objects.equals(this.format, screenshotOptions.format) &&
        Objects.equals(this.quality, screenshotOptions.quality) &&
        Objects.equals(this.userAgent, screenshotOptions.userAgent) &&
        Objects.equals(this.javascript, screenshotOptions.javascript) &&
        Objects.equals(this.blockAds, screenshotOptions.blockAds) &&
        Objects.equals(this.acceptCookies, screenshotOptions.acceptCookies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(width, height, fullPage, waitTime, format, quality, userAgent, javascript, blockAds, acceptCookies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreenshotOptions {\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    fullPage: ").append(toIndentedString(fullPage)).append("\n");
    sb.append("    waitTime: ").append(toIndentedString(waitTime)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    javascript: ").append(toIndentedString(javascript)).append("\n");
    sb.append("    blockAds: ").append(toIndentedString(blockAds)).append("\n");
    sb.append("    acceptCookies: ").append(toIndentedString(acceptCookies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

