/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.whispersec.model.TechniqueConfig;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Configuration for generating similar domain variations for brand protection and threat hunting
 */
@JsonPropertyOrder({
  SimilarDomainRequest.JSON_PROPERTY_TECHNIQUES,
  SimilarDomainRequest.JSON_PROPERTY_LIMIT,
  SimilarDomainRequest.JSON_PROPERTY_CHECK_REGISTRATION,
  SimilarDomainRequest.JSON_PROPERTY_INCLUDE_DNS,
  SimilarDomainRequest.JSON_PROPERTY_INCLUDE_RISK_SCORE,
  SimilarDomainRequest.JSON_PROPERTY_TECHNIQUE_CONFIG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-01T14:38:21.899985563Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class SimilarDomainRequest {
  public static final String JSON_PROPERTY_TECHNIQUES = "techniques";
  @jakarta.annotation.Nullable
  private Set<String> techniques = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @jakarta.annotation.Nullable
  private Integer limit = 100;

  public static final String JSON_PROPERTY_CHECK_REGISTRATION = "check_registration";
  @jakarta.annotation.Nullable
  private Boolean checkRegistration = false;

  public static final String JSON_PROPERTY_INCLUDE_DNS = "include_dns";
  @jakarta.annotation.Nullable
  private Boolean includeDns = false;

  public static final String JSON_PROPERTY_INCLUDE_RISK_SCORE = "include_risk_score";
  @jakarta.annotation.Nullable
  private Boolean includeRiskScore = true;

  public static final String JSON_PROPERTY_TECHNIQUE_CONFIG = "technique_config";
  @jakarta.annotation.Nullable
  private TechniqueConfig techniqueConfig;

  public SimilarDomainRequest() {
  }

  public SimilarDomainRequest techniques(@jakarta.annotation.Nullable Set<String> techniques) {
    
    this.techniques = techniques;
    return this;
  }

  public SimilarDomainRequest addTechniquesItem(String techniquesItem) {
    if (this.techniques == null) {
      this.techniques = new LinkedHashSet<>();
    }
    this.techniques.add(techniquesItem);
    return this;
  }

  /**
   * Types of domain variations to generate
   * @return techniques
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TECHNIQUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getTechniques() {
    return techniques;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_TECHNIQUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTechniques(@jakarta.annotation.Nullable Set<String> techniques) {
    this.techniques = techniques;
  }

  public SimilarDomainRequest limit(@jakarta.annotation.Nullable Integer limit) {
    
    this.limit = limit;
    return this;
  }

  /**
   * Maximum number of similar domains to generate
   * minimum: 1
   * maximum: 1000
   * @return limit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@jakarta.annotation.Nullable Integer limit) {
    this.limit = limit;
  }

  public SimilarDomainRequest checkRegistration(@jakarta.annotation.Nullable Boolean checkRegistration) {
    
    this.checkRegistration = checkRegistration;
    return this;
  }

  /**
   * Check if generated domains are registered
   * @return checkRegistration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHECK_REGISTRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckRegistration() {
    return checkRegistration;
  }


  @JsonProperty(value = JSON_PROPERTY_CHECK_REGISTRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckRegistration(@jakarta.annotation.Nullable Boolean checkRegistration) {
    this.checkRegistration = checkRegistration;
  }

  public SimilarDomainRequest includeDns(@jakarta.annotation.Nullable Boolean includeDns) {
    
    this.includeDns = includeDns;
    return this;
  }

  /**
   * Include DNS resolution data for registered domains
   * @return includeDns
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_DNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeDns() {
    return includeDns;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_DNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeDns(@jakarta.annotation.Nullable Boolean includeDns) {
    this.includeDns = includeDns;
  }

  public SimilarDomainRequest includeRiskScore(@jakarta.annotation.Nullable Boolean includeRiskScore) {
    
    this.includeRiskScore = includeRiskScore;
    return this;
  }

  /**
   * Calculate risk scores for each variation
   * @return includeRiskScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_RISK_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeRiskScore() {
    return includeRiskScore;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_RISK_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeRiskScore(@jakarta.annotation.Nullable Boolean includeRiskScore) {
    this.includeRiskScore = includeRiskScore;
  }

  public SimilarDomainRequest techniqueConfig(@jakarta.annotation.Nullable TechniqueConfig techniqueConfig) {
    
    this.techniqueConfig = techniqueConfig;
    return this;
  }

  /**
   * Get techniqueConfig
   * @return techniqueConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TECHNIQUE_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TechniqueConfig getTechniqueConfig() {
    return techniqueConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_TECHNIQUE_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTechniqueConfig(@jakarta.annotation.Nullable TechniqueConfig techniqueConfig) {
    this.techniqueConfig = techniqueConfig;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimilarDomainRequest similarDomainRequest = (SimilarDomainRequest) o;
    return Objects.equals(this.techniques, similarDomainRequest.techniques) &&
        Objects.equals(this.limit, similarDomainRequest.limit) &&
        Objects.equals(this.checkRegistration, similarDomainRequest.checkRegistration) &&
        Objects.equals(this.includeDns, similarDomainRequest.includeDns) &&
        Objects.equals(this.includeRiskScore, similarDomainRequest.includeRiskScore) &&
        Objects.equals(this.techniqueConfig, similarDomainRequest.techniqueConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(techniques, limit, checkRegistration, includeDns, includeRiskScore, techniqueConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimilarDomainRequest {\n");
    sb.append("    techniques: ").append(toIndentedString(techniques)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    checkRegistration: ").append(toIndentedString(checkRegistration)).append("\n");
    sb.append("    includeDns: ").append(toIndentedString(includeDns)).append("\n");
    sb.append("    includeRiskScore: ").append(toIndentedString(includeRiskScore)).append("\n");
    sb.append("    techniqueConfig: ").append(toIndentedString(techniqueConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

