/*
 * Whisper Security API
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.whispersec.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Configuration for top-level domain variations
 */
@JsonPropertyOrder({
  TldVariationConfig.JSON_PROPERTY_COMMON_TLDS,
  TldVariationConfig.JSON_PROPERTY_COUNTRY_TLDS,
  TldVariationConfig.JSON_PROPERTY_NEW_GTLDS,
  TldVariationConfig.JSON_PROPERTY_CUSTOM_TLDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-01T14:38:21.899985563Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class TldVariationConfig {
  public static final String JSON_PROPERTY_COMMON_TLDS = "common_tlds";
  @jakarta.annotation.Nullable
  private Boolean commonTlds = true;

  public static final String JSON_PROPERTY_COUNTRY_TLDS = "country_tlds";
  @jakarta.annotation.Nullable
  private Boolean countryTlds = false;

  public static final String JSON_PROPERTY_NEW_GTLDS = "new_gtlds";
  @jakarta.annotation.Nullable
  private Boolean newGtlds = true;

  public static final String JSON_PROPERTY_CUSTOM_TLDS = "custom_tlds";
  @jakarta.annotation.Nullable
  private Set<String> customTlds = new LinkedHashSet<>();

  public TldVariationConfig() {
  }

  public TldVariationConfig commonTlds(@jakarta.annotation.Nullable Boolean commonTlds) {
    
    this.commonTlds = commonTlds;
    return this;
  }

  /**
   * Include common TLD variations (.com, .net, .org, etc.)
   * @return commonTlds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMON_TLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommonTlds() {
    return commonTlds;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMON_TLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommonTlds(@jakarta.annotation.Nullable Boolean commonTlds) {
    this.commonTlds = commonTlds;
  }

  public TldVariationConfig countryTlds(@jakarta.annotation.Nullable Boolean countryTlds) {
    
    this.countryTlds = countryTlds;
    return this;
  }

  /**
   * Include country-code TLDs
   * @return countryTlds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY_TLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCountryTlds() {
    return countryTlds;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY_TLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryTlds(@jakarta.annotation.Nullable Boolean countryTlds) {
    this.countryTlds = countryTlds;
  }

  public TldVariationConfig newGtlds(@jakarta.annotation.Nullable Boolean newGtlds) {
    
    this.newGtlds = newGtlds;
    return this;
  }

  /**
   * Include new generic TLDs (.app, .dev, .cloud, etc.)
   * @return newGtlds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEW_GTLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNewGtlds() {
    return newGtlds;
  }


  @JsonProperty(value = JSON_PROPERTY_NEW_GTLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewGtlds(@jakarta.annotation.Nullable Boolean newGtlds) {
    this.newGtlds = newGtlds;
  }

  public TldVariationConfig customTlds(@jakarta.annotation.Nullable Set<String> customTlds) {
    
    this.customTlds = customTlds;
    return this;
  }

  public TldVariationConfig addCustomTldsItem(String customTldsItem) {
    if (this.customTlds == null) {
      this.customTlds = new LinkedHashSet<>();
    }
    this.customTlds.add(customTldsItem);
    return this;
  }

  /**
   * Custom TLDs to check
   * @return customTlds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_TLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getCustomTlds() {
    return customTlds;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_TLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomTlds(@jakarta.annotation.Nullable Set<String> customTlds) {
    this.customTlds = customTlds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TldVariationConfig tldVariationConfig = (TldVariationConfig) o;
    return Objects.equals(this.commonTlds, tldVariationConfig.commonTlds) &&
        Objects.equals(this.countryTlds, tldVariationConfig.countryTlds) &&
        Objects.equals(this.newGtlds, tldVariationConfig.newGtlds) &&
        Objects.equals(this.customTlds, tldVariationConfig.customTlds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonTlds, countryTlds, newGtlds, customTlds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TldVariationConfig {\n");
    sb.append("    commonTlds: ").append(toIndentedString(commonTlds)).append("\n");
    sb.append("    countryTlds: ").append(toIndentedString(countryTlds)).append("\n");
    sb.append("    newGtlds: ").append(toIndentedString(newGtlds)).append("\n");
    sb.append("    customTlds: ").append(toIndentedString(customTlds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

